package UrbanVisuals.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Component;
  private ConceptPresentation props_DataGrid;
  private ConceptPresentation props_LabelInput;
  private ConceptPresentation props_Root;
  private ConceptPresentation props_Section;
  private ConceptPresentation props_VisualFile;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Component:
        if (props_Component == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_Component = cpb.create();
        }
        return props_Component;
      case LanguageConceptSwitch.DataGrid:
        if (props_DataGrid == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_DataGrid = cpb.create();
        }
        return props_DataGrid;
      case LanguageConceptSwitch.LabelInput:
        if (props_LabelInput == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_LabelInput = cpb.create();
        }
        return props_LabelInput;
      case LanguageConceptSwitch.Root:
        if (props_Root == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("root");
          props_Root = cpb.create();
        }
        return props_Root;
      case LanguageConceptSwitch.Section:
        if (props_Section == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Section = cpb.create();
        }
        return props_Section;
      case LanguageConceptSwitch.VisualFile:
        if (props_VisualFile == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_VisualFile = cpb.create();
        }
        return props_VisualFile;
    }
    return null;
  }
}
