package UrbanVisuals.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_LabelInputType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_LabelInputType() {
    super(0x84d162bfa6bd428dL, 0x9b7556edca8f6b21L, 0x772e8ab13d5d0db1L, "LabelInputType", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/8587954033285467569", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_text_0 = new EnumerationDescriptor.MemberDescriptor("text", "text", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/8587954033285467570", "text");
  private final EnumerationDescriptor.MemberDescriptor VALUE_date_0 = new EnumerationDescriptor.MemberDescriptor("date", "date", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/8587954033285467571", "date");
  private final EnumerationDescriptor.MemberDescriptor VALUE_number_0 = new EnumerationDescriptor.MemberDescriptor("number", "number", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/8587954033285467574", "number");
  private final EnumerationDescriptor.MemberDescriptor VALUE_currency_0 = new EnumerationDescriptor.MemberDescriptor("currency", "currency", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/8587954033285467578", "currency");
  private final EnumerationDescriptor.MemberDescriptor VALUE_textarea_0 = new EnumerationDescriptor.MemberDescriptor("textarea", "textarea", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/2626510300427289536", "textarea");
  private final EnumerationDescriptor.MemberDescriptor VALUE_select_0 = new EnumerationDescriptor.MemberDescriptor("select", "select", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/630875922893664392", "select");
  private final EnumerationDescriptor.MemberDescriptor VALUE_checkbox_0 = new EnumerationDescriptor.MemberDescriptor("checkbox", "checkbox", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/630875922894132212", "checkbox");
  private final EnumerationDescriptor.MemberDescriptor VALUE_radio_0 = new EnumerationDescriptor.MemberDescriptor("radio", "radio", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/5970663237920422794", "radio");
  private final EnumerationDescriptor.MemberDescriptor VALUE_contactLookUp_0 = new EnumerationDescriptor.MemberDescriptor("contactLookUp", "contactLookUp", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/5970663237921166803", "contactLookUp");
  private final EnumerationDescriptor.MemberDescriptor VALUE_legalvalue_0 = new EnumerationDescriptor.MemberDescriptor("legal value", "legal value", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/5970663237921330713", "legal value");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_text_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_text_0, VALUE_date_0, VALUE_number_0, VALUE_currency_0, VALUE_textarea_0, VALUE_select_0, VALUE_checkbox_0, VALUE_radio_0, VALUE_contactLookUp_0, VALUE_legalvalue_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "text":
        return VALUE_text_0;
      case "date":
        return VALUE_date_0;
      case "number":
        return VALUE_number_0;
      case "currency":
        return VALUE_currency_0;
      case "textarea":
        return VALUE_textarea_0;
      case "select":
        return VALUE_select_0;
      case "checkbox":
        return VALUE_checkbox_0;
      case "radio":
        return VALUE_radio_0;
      case "contactLookUp":
        return VALUE_contactLookUp_0;
      case "legal value":
        return VALUE_legalvalue_0;
    }
    return null;
  }
}
