package UrbanVisuals.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_FlexSize extends EnumerationDescriptorBase {

  public EnumerationDescriptor_FlexSize() {
    super(0x84d162bfa6bd428dL, 0x9b7556edca8f6b21L, 0x6be5cd2096f55136L, "FlexSize", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/7774845871580336438", PrimitiveTypeId.INTEGER);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_10_0 = new EnumerationDescriptor.MemberDescriptor("10", "10", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/7774845871580336440", "10");
  private final EnumerationDescriptor.MemberDescriptor VALUE_20_0 = new EnumerationDescriptor.MemberDescriptor("20", "20", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/7774845871580336439", "20");
  private final EnumerationDescriptor.MemberDescriptor VALUE_30_0 = new EnumerationDescriptor.MemberDescriptor("30", "30", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/7774845871580336443", "30");
  private final EnumerationDescriptor.MemberDescriptor VALUE_40_0 = new EnumerationDescriptor.MemberDescriptor("40", "40", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/7774845871580336447", "40");
  private final EnumerationDescriptor.MemberDescriptor VALUE_50_0 = new EnumerationDescriptor.MemberDescriptor("50", "50", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/7774845871580336452", "50");
  private final EnumerationDescriptor.MemberDescriptor VALUE_60_0 = new EnumerationDescriptor.MemberDescriptor("60", "60", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/7774845871580336458", "60");
  private final EnumerationDescriptor.MemberDescriptor VALUE_70_0 = new EnumerationDescriptor.MemberDescriptor("70", "70", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/7774845871580336465", "70");
  private final EnumerationDescriptor.MemberDescriptor VALUE_80_0 = new EnumerationDescriptor.MemberDescriptor("80", "80", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/7774845871580336473", "80");
  private final EnumerationDescriptor.MemberDescriptor VALUE_90_0 = new EnumerationDescriptor.MemberDescriptor("90", "90", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/7774845871580336482", "90");
  private final EnumerationDescriptor.MemberDescriptor VALUE_100_0 = new EnumerationDescriptor.MemberDescriptor("100", "100", "r:f376836f-9fc8-4f49-b551-418ce2d5073b(UrbanVisuals.structure)/7774845871580336492", "100");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_100_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_10_0, VALUE_20_0, VALUE_30_0, VALUE_40_0, VALUE_50_0, VALUE_60_0, VALUE_70_0, VALUE_80_0, VALUE_90_0, VALUE_100_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "10":
        return VALUE_10_0;
      case "20":
        return VALUE_20_0;
      case "30":
        return VALUE_30_0;
      case "40":
        return VALUE_40_0;
      case "50":
        return VALUE_50_0;
      case "60":
        return VALUE_60_0;
      case "70":
        return VALUE_70_0;
      case "80":
        return VALUE_80_0;
      case "90":
        return VALUE_90_0;
      case "100":
        return VALUE_100_0;
    }
    return null;
  }
}
